CORE-41 Add MinIO as default storage provider (#1127)
* wip: adding minio

* wip: minio

* feat: add minIO as default storage provider

* Expose console

https://stackoverflow.com/questions/69079602/docker-unable-to-access-minio-web-browser

* Fix AttributeError: 'int' object has no attribute 'isnumeric'

Becuase option = 1 , so then option.isnumeric() doesn't exit
Some duplicatation with set_static_storage_option() twice
but seemed more clear then an or statment on same line

* fix: minio host conflicts for docker compose ctx

* fix: proxy redirect for minio media

After a lot of research and investigation, I ended up creating a proxy on the dispatcher for all the media routes to MinIO.

Co-authored-by: Anthony Sarkis <18080164+anthony-sarkis@users.noreply.github.com>