DAD-28 Time Tracking (#576)
* wip: adding support to new reports

* wip: track time endpoint

* wip: models alembic migrations and unit tests

* wip: unit tests time track create

* wip: time tracking tests

* wip: readd test

* feat: add endpoint and unit tests

* feat: added time tracker frontend component and save functionality

Added on image/video UI. Pending the 3D UI

* feat: add track time custom report implementation

Pending per user grouping and improvements on filters

* wip: components time tracking reports

* wip: add time tracking UI to ui schema

* wip: report data setup

* fea: added charts on job section

* wip: reports

* feat: add users filter to report

* fix: rout change on new tab

* fix: add autocomplete to member select on stats panel

* fix: e2e tests

* fix: e2e tests

* fix: task template creation

* fix: task template creation test e2e

* fix: unit tests

* fix: change parallelism

* Improve: Move Task buttons to new task menu

Opinion: Small reorder of new exam higher, to align with new task / task list

* Fix: Syntax error on 'null'

sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "null"
LINE 4: WHERE task.assignee_user_id = 'null' AND task.job_id =....

Reproduction was when clearing current user on stats

* Suggestion: Only start time on incomplete tasks

Or if it's better to track all and filter it on the backend that's good too
For v1 this seemed like easiest , that way admin users can review completed work without increasing time.

* fix: hide instances only after succesful task change 

Also better loading placeholder and show dialog instead of snackbar on last task.

* fix: e2e test

Co-authored-by: Pablo <pjestradac@gmail.com>
Co-authored-by: Anthony Sarkis <18080164+anthony-sarkis@users.noreply.github.com>